### ISSUE TITLE
Ansible playbooks raise many deprecation errors version 2.0

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/wagtail-cookiecutter-foundation#268]
For example we're seeing this a lot

```
instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default).
```
We are also seeing a number of old style environment references. We need to check and fix the following 

- [x] deploy.yml
- [x] roles/common
- [x] roles/database
- [x] roles/web

**Comment by chrisdev** [comment]
```yml
#Old Way with sudo and user
- name: apply common configruation to all nodes
  hosts: all 
  sudo: yes 
  user: root 
  roles:
      - common


#New way set remote user/become_user

- name: apply common configruation to all nodes
  hosts: all 
  remote_user: django 
  become: yes
  become_user: root
  roles:
      - common

```
